# Generated by Django 5.2.6 on 2025-10-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_products_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='products_views',
            field=models.IntegerField(default=0),
        ),
    ]
